apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  # labels:
  #   app: myapp
  #   key: value
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:2
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod  # igual ao metadata acima (linha 13)
